name: Pelletier + Schaar Stock Plans
favicon: null
layout_spectrum: 0.4692421113140881
typography_spectrum: 0.5696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#97b5a9'
    - '#b7c6bf'
    - '#cfddd8'
    - '#eaf3ee'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
