name: Pelletier + Schaar Stock Plans
favicon: null
layout_spectrum: 0.4692421113140881
typography_spectrum: 0.5696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#201e21'
    - '#c2c0c3'
    - '#84918a'
    - '#885331'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
